server:
  port: 8088
  shutdown: graceful
  servlet:
    context-path: /profile

api:
  version: v1
  prefix:
    secure: /api/${api.version}
    open: /open/${api.version}
    internal: /_api/${api.version}

spring:
  application:
    name: profile

  kafka:
    consumer:
      group-id: authentication
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  instance:
    metadata-map:
      prometheus.path: /profile/actuator/prometheus
      context.path: /profile



springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html



management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true


keycloak:
  realm: admin-exchange
  auth-server-url: http://localhost:8080
  client-id: exchange-management
  client-secret: 3j8ultDup3u5v4nxczkm5lco65NL0aXX


