spring:
  data:
    redis:
      host: redis
      port: 6379
      database: 0
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  kafka:
    bootstrap-servers: kafka:9092




minio:
  endpoint: http://minio:9000
  secret-Key: gOUzGcRszSocFWcgpOCWbauBtnT3IYfPvjoa26FM
  access-key: X7ttdLWc5g1E1pwdp8aN
  bucket: profile
  file:
    url:
      prefix: http://127.0.0.1:9000