spring:
  datasource:
    username: user_auth
    password: secretpassauth
    url: jdbc:postgresql://localhost:5432/exchange_auth
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092




