spring:
  datasource:
    username: user_oms
    password: secretpassoms
    url: jdbc:postgresql://localhost:5432/exchange_oms
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092



custom-config:
  kafka:
    updatematchingEngine-input-message:
      topic: updatematchingEngine-message


